spring.application.name=GeObras_2

spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=GeObras;encrypt=false
spring.datasource.username=sa
spring.datasource.password=cassioli
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.datasource.hikari.maximum-pool-size=1
spring.datasource.hikari.connection-timeout=10000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true   